---
- name: install ha required packages
  yum: 
    name: "{{ ha_pkg}}"
    state: latest 
  when: inventory_hostname in  groups['master']

- name: upload haproxy conf file
  copy: 
    src: "{{ haproxy_src }}"
    dest: "{{ haproxy_dest }}"
  when: inventory_hostname in  groups['master']

- name: upload keepalived master conf
  copy: 
    src: "{{ ha_keep_master }}"
    dest: "{{ ha_keep_dest }}"
  when: inventory_hostname == 'master1.example.local'

- name: upload keepalived backup conf
  copy: 
    src: "{{ ha_keep_bkp }}"
    dest: "{{ ha_keep_dest }}"
  when: inventory_hostname in  groups['backup']

- name: upload check api script
  copy: 
    src: "{{ ha_chk_src }}"
    dest: "{{ ha_chk_dest }}"
  when: inventory_hostname in  groups['master']

- name: modify kernel parameters
  sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_file: "{{ sysctl_file }}"
    sysctl_set: yes
  loop: "{{ k8s_kernels }}"
  when: inventory_hostname in  groups['master']


- name: setup sebollean for haproxy 
  seboolean:
    name: haproxy_connect_any
    state: yes
    persistent: yes
  when: inventory_hostname in  groups['master']

- name: start ha svc
  service: 
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ ha_svc }}"
  when: inventory_hostname in  groups['master']